chore: added analytics and speedinsights from vercel
defi-wonderland/superchain-bridge-ui pull request #44
Opened 2024-03-22 16:19 UTC by 0xtiti

## analytics and speedinsights from vercel

## Checklist before requesting a review

- [x] I have conducted a self-review of my code.
- [ ] If it is a core feature, I have included comprehensive tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one sentence about this update.

2024-03-22 19:50 UTC, 0xArdy requested changes

2024-03-22 19:50 UTC, 0xArdy commented on package.json
> +    "@vercel/speed-insights": "^1.0.10",
remember to lock the dependencies version

2024-03-22 19:50 UTC, 0xArdy commented on yarn.lock
this file isn't necessary

2024-03-22 19:53 UTC, 0xArdy commented
you can add `closes <SUP XX>` in the pr description and thenit automatically mark the issue as done once the pr is merged

2024-03-25 01:07 UTC, 0xtiti commented on package.json
> +    "@vercel/speed-insights": "^1.0.10",
sorry about that!

2024-03-25 02:22 UTC, 0xtiti commented on package.json
> +    "@vercel/speed-insights": "^1.0.10",
https://github.com/defi-wonderland/superchain-bridge-ui/commit/a8000c604958f24c8d6caacc2891766bb39497c7

2024-03-25 02:22 UTC, 0xtiti commented on yarn.lock
https://github.com/defi-wonderland/superchain-bridge-ui/commit/a8000c604958f24c8d6caacc2891766bb39497c7

2024-03-25 11:51 UTC, 0xArdy approved these changes
lgtm! :rocket:

2024-03-25 11:52 UTC, merged

2024-03-25 21:09 UTC, turtlemoji commented
reviewed