feat: UI enhancements
defi-wonderland/superchain-bridge-ui pull request #47
Opened 2024-03-25 23:42 UTC by 0xtiti

## Describe your changes

- Add toggle for expert mode
- Add copy to clipboard functionality
- Add refresh button in account history

## Issue ticket number and link

closes SUP-72
closes SUP-79
closes SUP-80

## Checklist before requesting a review

- [x] I have conducted a self-review of my code.
- [ ] If it is a core feature, I have included comprehensive tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one sentence about this update.

2024-03-26 12:35 UTC, 0xArdy requested changes
great work! remember to update your branch with dev and resolve conflicts

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +        gap: 'var(--spacing-2xl, 1.25rem)',
we are not using vars, also i think the gap should be bigger :thinking: 
```suggestion
        gap: '1.25rem',
```

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +      },
on mobile i think a little more horizontal padding can make it look better

![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/bdfa311a-1f9e-4f6e-a43f-5d309eaefb18)

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +        minWidth: '13rem',
I know it's not in the design, but you can set the font size to `1.4rem` on mobile please. I think `1.6rem` is too big for small screens

2024-03-26 12:35 UTC, 0xArdy commented on src/pages/[chain]/account/[account]/index.tsx
> +            <IconButton onClick={refetchLogs}>
Since we don't have the design yet, I think it's better to hide this refresh button on mobile devices

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/TransactionDetails/TxDetails.tsx
> +                <Image
We need more distance between the text and the hover effect on the button

![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/bbaceb8f-1d65-42e5-b6d8-6d79405a9b9c)

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +export const SBox = styled(Box)(() => {
where do u use this component?

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +    height: 24,
idem

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +      height: 20,
idem. use rem units please

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/Modals/Review.tsx
> +      height: '32px',
idem

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/TransactionDetails/TxDetails.tsx
> +  const copiedTextTimeout = 800;
i think we can better get that variable from the `useCopyToClipboard` hook

2024-03-26 12:35 UTC, 0xArdy commented on src/containers/Modals/Review.tsx
> +  };
i think all that logic can be abstracted on the `useCopyToClipboard` hook, to avoid defining all that state variables and functions every time we want to copy several things. wdyt?

2024-03-26 12:52 UTC, 0xtiti commented on src/containers/Modals/Review.tsx
> +  };
This issue is also due to origin and destination can be the same address, then it gets harder to identify

2024-03-26 17:05 UTC, turtlemoji commented on src/containers/BridgeCard/CardHeader.tsx
> +              <ExpertModeSwitch checked={isExpertMode} onChange={activateExpertMode} disableRipple />
I recommend to change `activateExpertMode` to `toggleExpertMode`

2024-03-26 17:06 UTC, turtlemoji commented on src/containers/BridgeCard/CardHeader.tsx
> +      minHeight: '72px',
+

2024-03-26 17:06 UTC, turtlemoji commented on src/containers/BridgeCard/CardHeader.tsx
> +export const SBox = styled(Box)(() => {
+

2024-03-26 17:26 UTC, 0xtiti commented on src/assets/icons/refresh.svg
eb39c05

2024-03-26 17:26 UTC, 0xtiti commented on src/pages/[chain]/account/[account]/index.tsx
> +            </IconButton>
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +      minHeight: '72px',
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +        gap: 'var(--spacing-2xl, 1.25rem)',
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +      },
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +    height: 24,
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/Modals/Review.tsx
> +      height: '32px',
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/TransactionDetails/TxDetails.tsx
> +  const copiedTextTimeout = 800;
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/Modals/Review.tsx
> +  };
eb39c05

2024-03-26 17:27 UTC, 0xtiti commented on src/containers/Modals/Review.tsx
> +  };
c1a2d59

2024-03-26 17:28 UTC, 0xtiti commented on src/containers/TransactionDetails/TxDetails.tsx
> +  const copiedTextTimeout = 800;
c1a2d59

2024-03-26 17:30 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +              <ExpertModeSwitch checked={isExpertMode} onChange={activateExpertMode} disableRipple />
9aa89ef

2024-03-27 14:13 UTC, 0xtiti commented on src/containers/TransactionDetails/TxDetails.tsx
> +                <Image
bea3d91cf56015a1c9511a41bdf346fd4dc998a3

2024-03-27 14:13 UTC, 0xtiti commented on src/pages/[chain]/account/[account]/index.tsx
> +            <IconButton onClick={refetchLogs}>
bea3d91cf56015a1c9511a41bdf346fd4dc998a3

2024-03-27 14:13 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +        minWidth: '13rem',
bea3d91cf56015a1c9511a41bdf346fd4dc998a3

2024-03-27 14:13 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +export const SBox = styled(Box)(() => {
no changes on this component from prev branch (dev)

2024-03-27 14:20 UTC, 0xArdy commented on src/containers/BridgeCard/CardHeader.tsx
> +        minWidth: '13rem',
it still shows a fontsize of 1.6rem
![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/f0c8ef51-4543-40aa-93bc-faa41d3afea5)

2024-03-27 16:22 UTC, 0xtiti commented on src/containers/BridgeCard/CardHeader.tsx
> +        minWidth: '13rem',
sorry about that, should be fine now: 8ab0549181dcc4d5cec3e281521640536670d36b

2024-03-27 17:13 UTC, 0xArdy submitted a review, later dismissed
:rocket:

2024-03-27 18:24 UTC, 0xArdy approved these changes

2024-03-27 18:24 UTC, merged