feat: notification chip
defi-wonderland/superchain-bridge-ui pull request #55
Opened 2024-03-28 06:32 UTC by 0xtiti

closes SUP-73

2024-03-28 13:52 UTC, 0xArdy requested changes
great implementation!

2024-03-28 13:52 UTC, 0xArdy commented on src/assets/icons/warning.svg
Why? this changes the Withdrawal warning modal
![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/7fe90252-9177-4810-8cfe-a9f467c556a5)

![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/20eebdf5-7619-4278-9783-5f67948612c8)

2024-03-28 13:52 UTC, 0xArdy commented on src/containers/BridgeCard/NotificationChip.tsx
> +export const CustomChip = styled(Chip)(() => ({
Hover effect needs improvement, maybe a lighter yellow as a background color
![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/1573d3a0-0c19-4330-8092-dff46323439c)

2024-03-28 13:52 UTC, 0xArdy commented on src/containers/BridgeCard/NotificationChip.tsx
> +};
just as a general comment, we need to add more vertical space between sections, to have more readable code

2024-03-28 13:52 UTC, 0xArdy commented on src/containers/BridgeCard/NotificationChip.tsx
It should be on `components` folder

2024-03-28 13:52 UTC, 0xArdy commented on src/containers/Landing.tsx
>  export const Landing = () => {
```suggestion
import { useLogs } from '~/hooks';

export const Landing = () => {
```

2024-03-28 13:52 UTC, 0xArdy commented on src/containers/Header.tsx
> +                  <Badge invisible={pendingTransactionCount === 0} variant='dot' color='primary' overlap='circular'>
I think this is more concise, but up to u
```suggestion
                  <Badge invisible={!pendingTransactionCount} variant='dot' color='primary' overlap='circular'>
```

2024-03-28 14:35 UTC, 0xtiti commented on src/assets/icons/warning.svg
fixed! My bad I overwrite it dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 14:35 UTC, 0xtiti commented on src/containers/BridgeCard/NotificationChip.tsx
> +export const CustomChip = styled(Chip)(() => ({
dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 14:35 UTC, 0xtiti commented on src/containers/BridgeCard/NotificationChip.tsx
> +};
dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 14:35 UTC, 0xtiti commented on src/containers/BridgeCard/NotificationChip.tsx
dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 14:35 UTC, 0xtiti commented on src/containers/Landing.tsx
>  export const Landing = () => {
dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 14:35 UTC, 0xtiti commented on src/containers/Header.tsx
> +                  <Badge invisible={pendingTransactionCount === 0} variant='dot' color='primary' overlap='circular'>
dafd24225f192ca7cb45d6b30823c5035ff3afab

2024-03-28 16:37 UTC, 0xArdy requested changes

2024-03-28 16:37 UTC, 0xArdy commented on src/components/NotificationChip.tsx
> +  left: '50%',
great! but on mobile we need to adopt a different approach bc it stays fixed like the header

![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/d4f55bb7-ab66-4ab8-b925-118f226a5e17)

2024-03-29 13:54 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +  left: '50%',
c18ad957de47ef1b92f9fda4d67ea3dff7978732

2024-03-29 13:57 UTC, 0xArdy submitted a review, later dismissed
:fire:

2024-03-29 18:44 UTC, turtlemoji commented on src/containers/Landing.tsx
> +      {pendingTransactionCount > 0 && <NotificationChip />}
```suggestion
      {!!pendingTransactionCount && <NotificationChip />}
```

2024-03-29 19:03 UTC, turtlemoji commented on src/providers/LogsProvider.tsx
> +      return logs.filter((log) => log.status.includes('waiting-') || log.status.includes('ready-to')).length;
why you check for .length on the second || ?

2024-03-29 19:04 UTC, turtlemoji commented on src/providers/LogsProvider.tsx
> +    return 0;
@0xtiti do you think it is better to skip the use of the temporal `isTransactionPeding` var in here to your criteria? I'm thinking about readability.

wdyt @0xArdy ?

2024-03-29 19:12 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +          {`${pendingTransactionCount} transaction${pendingTransactionCount > 1 ? 's' : ''} requires action`}
```suggestion
  const transactionText = pendingTransactionCount + 
                          pendingTransactionCount > 1 ? ' transactions' : ' transaction' +
                          ' requires action';

  return (
    <CustomChip
      label={
        <div className='chip-container'>
          <WarningIcon />
          {transactionText}
```

2024-03-29 19:20 UTC, 0xArdy commented on src/providers/LogsProvider.tsx
> +    return 0;
now we return the number of pending transactions and `isTransactionPending` is no longer needed. im ok returning 0 to have `pendingTransactionCount: number`

2024-03-29 19:22 UTC, 0xArdy commented on src/providers/LogsProvider.tsx
> +      return logs.filter((log) => log.status.includes('waiting-') || log.status.includes('ready-to')).length;
It isnt after `||`. Its after the `filter` to return the number of pending transactions

2024-03-29 19:30 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +          {`${pendingTransactionCount} transaction${pendingTransactionCount > 1 ? 's' : ''} requires action`}
```suggestion
  const notificationChipText = `${pendingTransactionCount} ${pendingTransactionCount > 1 ? 'transactions' : 'transaction'} requires action`;

  return (
    <CustomChip
      label={
        <div className='chip-container'>
          <WarningIcon />
          {`${pendingTransactionCount} transaction${pendingTransactionCount > 1 ? 's' : ''} requires action`}
```

2024-03-29 19:31 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +          {`${pendingTransactionCount} transaction${pendingTransactionCount > 1 ? 's' : ''} requires action`}
We try to avoid logic on the HTML when possible

2024-03-29 19:34 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +  background: '#291205',
hardcoded vars?

2024-03-29 19:34 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +  color: '#FFD27A',
idem

2024-03-29 19:34 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +  position: 'fixed',
better to be absolute, and the parent be relative to avoid scroll issues if possible

2024-03-29 19:35 UTC, turtlemoji commented on src/components/NotificationChip.tsx
> +    paddingRight: '0px',
```suggestion
    paddingLeft: '0',
    paddingRight: '0',
```
Maybe would be better, lets @0xArdy decide

2024-03-29 19:36 UTC, turtlemoji commented on src/providers/LogsProvider.tsx
> +      return logs.filter((log) => log.status.includes('waiting-') || log.status.includes('ready-to')).length;
oh lmao you are right!

2024-03-29 19:36 UTC, turtlemoji commented on src/providers/LogsProvider.tsx
> +    return 0;
perfect then!

2024-04-01 16:48 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +          {`${pendingTransactionCount} transaction${pendingTransactionCount > 1 ? 's' : ''} requires action`}
https://github.com/defi-wonderland/superchain-bridge-ui/commit/b159a4984a41df858c068659619262acc2109e43

2024-04-01 16:48 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +  background: '#291205',
https://github.com/defi-wonderland/superchain-bridge-ui/commit/b159a4984a41df858c068659619262acc2109e43

2024-04-01 16:48 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +  color: '#FFD27A',
https://github.com/defi-wonderland/superchain-bridge-ui/commit/b159a4984a41df858c068659619262acc2109e43

2024-04-01 16:48 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +  position: 'fixed',
https://github.com/defi-wonderland/superchain-bridge-ui/commit/b159a4984a41df858c068659619262acc2109e43

2024-04-01 16:48 UTC, 0xtiti commented on src/components/NotificationChip.tsx
> +    paddingRight: '0px',
https://github.com/defi-wonderland/superchain-bridge-ui/commit/b159a4984a41df858c068659619262acc2109e43

2024-04-01 19:27 UTC, 0xArdy approved these changes

2024-04-03 03:47 UTC, turtlemoji approved these changes

2024-04-03 03:58 UTC, merged