fix: token input decimals
defi-wonderland/superchain-bridge-ui pull request #57
Opened 2024-03-28 13:30 UTC by 0xtiti

closes SUP-93

2024-03-28 15:36 UTC, 0xArdy requested changes

2024-03-28 15:36 UTC, 0xArdy commented on src/containers/BridgeCard/TokenSection.tsx
> -    },
lol some styles broke, sorry i think those lines were necessary
![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/02fef33a-784a-47c4-a63c-75ed071c136d)

2024-03-29 13:55 UTC, 0xtiti commented on src/containers/BridgeCard/TokenSection.tsx
> -    },
897e445bb1aed59abb077fb042233ef8201371b3

2024-03-29 13:55 UTC, 0xArdy approved these changes
lgtm! :rocket:

2024-03-29 19:39 UTC, turtlemoji commented on src/containers/BridgeCard/TokenSection.tsx
> +    isEth ? setEthValue(normalizedInput) : setAmount(normalizedInput);
```suggestion
    if (isEth) {
         setEthValue(normalizedInput)
    } else {
        setAmount(normalizedInput);
    }
```

2024-03-29 19:41 UTC, turtlemoji commented on src/containers/BridgeCard/TokenSection.tsx
> +    const normalizedInput = e.target.value.replace(/[^0-9.]+/g, '').replace(/(\..*)\..*/g, '$1');
A comment could add value here, so, it seems to remove everything except numbers and dots right?

2024-03-29 19:43 UTC, turtlemoji commented on src/containers/BridgeCard/TokenSection.tsx
> +    isEth ? setEthValue(normalizedInput) : setAmount(normalizedInput);
just for readability

2024-03-29 19:44 UTC, turtlemoji approved these changes
pre-approved with some comments

2024-04-01 16:16 UTC, 0xtiti commented on src/containers/BridgeCard/TokenSection.tsx
> +    const normalizedInput = e.target.value.replace(/[^0-9.]+/g, '').replace(/(\..*)\..*/g, '$1');
https://github.com/defi-wonderland/superchain-bridge-ui/pull/57/commits/5c86f870db2191d10e3924cf3605277363aabaec

2024-04-01 16:16 UTC, 0xtiti commented on src/containers/BridgeCard/TokenSection.tsx
> +    const normalizedInput = e.target.value.replace(/[^0-9.]+/g, '').replace(/(\..*)\..*/g, '$1');
https://github.com/defi-wonderland/superchain-bridge-ui/pull/57/commits/5c86f870db2191d10e3924cf3605277363aabaec

2024-04-01 16:16 UTC, 0xtiti commented on src/containers/BridgeCard/TokenSection.tsx
> +    isEth ? setEthValue(normalizedInput) : setAmount(normalizedInput);
https://github.com/defi-wonderland/superchain-bridge-ui/pull/57/commits/5c86f870db2191d10e3924cf3605277363aabaec

2024-04-01 17:54 UTC, 0xArdy approved these changes

2024-04-03 03:58 UTC, merged