feat:token-price
defi-wonderland/superchain-bridge-ui pull request #61
Opened 2024-04-01 20:03 UTC by 0xtiti

closes SUP-66

2024-04-04 12:51 UTC, 0xArdy requested changes
great implementation!

Have you tested it on mainnet?

2024-04-04 12:51 UTC, 0xArdy commented on src/providers/TokenProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
why?

2024-04-04 12:51 UTC, 0xArdy commented on .env.example
> +NEXT_PUBLIC_COINGECKO_KEY= # API key from COINGECKO
you can delete it since it's not used

2024-04-04 12:51 UTC, 0xArdy commented on src/config/env.ts
> +    COINGECKO_KEY: process.env.NEXT_PUBLIC_COINGECKO_KEY || '',
idem

2024-04-04 12:51 UTC, 0xArdy commented on src/types/config.ts
> +  COINGECKO_KEY: string;
idem

2024-04-04 17:52 UTC, 0xtiti commented on src/providers/TokenProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
didn't think toTokenS was needed on the dependency array and that was causing eslint warning, but I added the [...fromToken, toTokenS] now :)  https://github.com/defi-wonderland/superchain-bridge-ui/pull/61/commits/9b923efdca5b5e4684c3d0c2e60675eb5a692687

2024-04-04 17:52 UTC, 0xtiti commented on .env.example
> +NEXT_PUBLIC_COINGECKO_KEY= # API key from COINGECKO
https://github.com/defi-wonderland/superchain-bridge-ui/pull/61/commits/9b923efdca5b5e4684c3d0c2e60675eb5a692687

2024-04-04 17:52 UTC, 0xtiti commented on src/config/env.ts
> +    COINGECKO_KEY: process.env.NEXT_PUBLIC_COINGECKO_KEY || '',
https://github.com/defi-wonderland/superchain-bridge-ui/pull/61/commits/9b923efdca5b5e4684c3d0c2e60675eb5a692687

2024-04-04 17:52 UTC, 0xtiti commented on src/types/config.ts
> +  COINGECKO_KEY: string;
https://github.com/defi-wonderland/superchain-bridge-ui/pull/61/commits/9b923efdca5b5e4684c3d0c2e60675eb5a692687

2024-04-04 21:51 UTC, turtlemoji commented on src/utils/getTokenPrice.ts
> +  Sepolia: 'ethereum', // Sepolia to Ethereum mainnet
```suggestion
  'Sepolia': 'ethereum', // Sepolia to Ethereum mainnet
```

2024-04-07 17:53 UTC, 0xtiti commented on src/utils/getTokenPrice.ts
> +  Sepolia: 'ethereum', // Sepolia to Ethereum mainnet
<img width="534" alt="Screen Shot 2024-04-07 at 14 38 22" src="https://github.com/defi-wonderland/superchain-bridge-ui/assets/162849030/c48b20fa-03a7-487e-b6b7-1c367e2b8d3c">

In this case, since Sepolia contains no space it doesn't need quotes and is still a string. If the key contains space then it needs quotes. Unfortunately, even if wanting to add '' for readability esLint and prettier wont let me and rules would need to be overwrite son in this scenario I would leave it without ''

2024-04-09 15:53 UTC, 0xShaito approved these changes

2024-04-09 15:53 UTC, 0xShaito commented on src/providers/TokenProvider.tsx
> +  const [price, setPrice] = useState<number>(0);
Wouldn't this be better started as undefined so we can show a loading or hide elements?

2024-04-09 16:47 UTC, turtlemoji commented on src/utils/getTokenPrice.ts
> +  Sepolia: 'ethereum', // Sepolia to Ethereum mainnet
yeah, normally is a bad practice to add spaces to a key in a map.

Thats why it prefers it without it normally :'(

2024-04-09 16:48 UTC, turtlemoji commented on src/providers/TokenProvider.tsx
> +  const [price, setPrice] = useState<number>(0);
+

2024-04-09 16:56 UTC, 0xtiti commented on src/providers/TokenProvider.tsx
> +  const [price, setPrice] = useState<number>(0);
Could be, I will need this to calculate the fees in the next PR so I will reconsider to change it to undefined instead

2024-04-09 16:56 UTC, merged