feat: testnet subdomain
defi-wonderland/superchain-bridge-ui pull request #68
Opened 2024-04-12 15:52 UTC by 0xtiti

closes SUP-102

2024-04-15 19:14 UTC, 0xArdy requested changes
great implementation! :fire: 
just some smol comments

2024-04-15 19:14 UTC, 0xArdy commented on src/providers/ChainProvider.tsx
>    const [fromChain, setFromChain] = useState<Chain>(availableChains[0] as Chain);
add more break lines to improve the readability of the code
```suggestion
  const { isTestnet, isReady } = useTestnet();
  
  const availableChains = useMemo(() => {
    return config.chains.filter((chain: Chain) => (isTestnet ? chain.testnet : !chain.testnet));
  }, [config.chains, isTestnet]);
  
  const [fromChain, setFromChain] = useState<Chain>(availableChains[0] as Chain);
```

2024-04-15 19:14 UTC, 0xArdy commented on src/hooks/useTestnet.ts
> +    if (typeof window !== 'undefined' && router.isReady) {
is `router.isReady` really required here?

2024-04-15 19:14 UTC, 0xArdy commented on src/containers/Footer.tsx
> +        )}
we recommend to use the `&&` operator instead of the ternary operator on the html/render section

2024-04-16 00:25 UTC, 0xtiti commented on src/containers/Footer.tsx
> +        )}
But in order to switch from mainnet to testnet and viceversa, shouldn't it be done this way instead of &&? In this case, since both options should show up based on subdomain

2024-04-16 10:03 UTC, 0xtiti commented on src/hooks/useTestnet.ts
> +    if (typeof window !== 'undefined' && router.isReady) {
removed [7a00940](https://github.com/defi-wonderland/superchain-bridge-ui/pull/68/commits/7a00940d0fc9350b88e0b1107bfbb172a5c2d4b7)

2024-04-16 11:50 UTC, 0xArdy approved these changes
lgtm!

2024-04-16 12:22 UTC, 0xArdy approved these changes
:fire:

2024-04-16 12:56 UTC, agusduha submitted a review, later dismissed

2024-04-16 13:07 UTC, 0xArdy approved these changes

2024-04-16 13:08 UTC, merged