feat: testnet label
defi-wonderland/superchain-bridge-ui pull request #77
Opened 2024-04-18 12:21 UTC by 0xtiti

2024-04-18 15:57 UTC, 0xArdy requested changes

2024-04-18 15:57 UTC, 0xArdy commented on src/containers/Header.tsx
> +          <StyledLabel className='testnet-label'>testnet</StyledLabel>
it should appear only in the testnet ui

2024-04-18 15:57 UTC, 0xArdy commented on src/containers/Header.tsx
> +      top: '-0.1rem',
it should be vertically aligned on mobile
![image](https://github.com/defi-wonderland/superchain-bridge-ui/assets/116569704/b379830d-0b43-4861-930d-d36e43a1f355)

2024-04-18 16:41 UTC, 0xtiti commented on src/containers/Header.tsx
> +      top: '-0.1rem',
[a1a72f0](https://github.com/defi-wonderland/superchain-bridge-ui/pull/77/commits/a1a72f0c4815149c46e30365a32eba4953f3afcc)

2024-04-18 16:41 UTC, 0xtiti commented on src/containers/Header.tsx
> +          <StyledLabel className='testnet-label'>testnet</StyledLabel>
sorry about missing this! 👀   [a1a72f0](https://github.com/defi-wonderland/superchain-bridge-ui/pull/77/commits/a1a72f0c4815149c46e30365a32eba4953f3afcc)

2024-04-18 22:15 UTC, 0xArdy approved these changes
lgtm!

2024-04-22 13:25 UTC, agusduha approved these changes

2024-04-22 13:29 UTC, merged