fix: i18n
defi-wonderland/superchain-bridge-ui pull request #81
Opened 2024-04-19 12:45 UTC by 0xtiti

2024-04-19 14:29 UTC, 0xArdy requested changes

2024-04-19 14:29 UTC, 0xArdy commented on src/pages/[chain]/index.tsx
> +    //it will check first for browser language
```suggestion
    // it will check first for browser language
```

2024-04-19 14:29 UTC, 0xArdy commented on src/pages/[chain]/index.tsx
> +    const locale = localStorage.getItem('bridgg-locale') || language || 'en';
i think the final hardcoded option `'en'` is no longer necessary

2024-04-19 14:29 UTC, 0xArdy commented on src/hooks/useQueryParams.tsx
> +        const supportedLocales = ['en', 'es'];
we should get the `supportedLocales` from the router (or constants). Letting them hardcoded here will cause us problems in the future

2024-04-19 14:29 UTC, 0xArdy commented on src/hooks/useBrowserLanguage.tsx
> +    setLanguage(browserLanguage.startsWith('es') ? 'es' : 'en');
we should generalize this, because we'll add more languages soon.

(but we can do it in a different pr)

2024-04-19 14:29 UTC, 0xArdy commented on src/hooks/useBrowserLanguage.tsx
> +  const [language, setLanguage] = useState<string>('en');
would be nice to have the default language in constants so we can replace `'en'` to `DEFAULT_LANG` everywhere

2024-04-19 18:05 UTC, 0xtiti commented on src/hooks/useBrowserLanguage.tsx
> +  const [language, setLanguage] = useState<string>('en');
[447619f](https://github.com/defi-wonderland/superchain-bridge-ui/pull/81/commits/447619f559bd4d8a08cf4e1cf357d83d33edc225)

2024-04-19 18:05 UTC, 0xtiti commented on src/hooks/useBrowserLanguage.tsx
> +    setLanguage(browserLanguage.startsWith('es') ? 'es' : 'en');
done! [447619f](https://github.com/defi-wonderland/superchain-bridge-ui/pull/81/commits/447619f559bd4d8a08cf4e1cf357d83d33edc225)

2024-04-19 18:05 UTC, 0xtiti commented on src/hooks/useQueryParams.tsx
> +        const supportedLocales = ['en', 'es'];
[447619f](https://github.com/defi-wonderland/superchain-bridge-ui/pull/81/commits/447619f559bd4d8a08cf4e1cf357d83d33edc225)

2024-04-19 18:05 UTC, 0xtiti commented on src/pages/[chain]/index.tsx
> +    const locale = localStorage.getItem('bridgg-locale') || language || 'en';
[447619f](https://github.com/defi-wonderland/superchain-bridge-ui/pull/81/commits/447619f559bd4d8a08cf4e1cf357d83d33edc225)

2024-04-19 18:05 UTC, 0xtiti commented on src/pages/[chain]/index.tsx
> +    //it will check first for browser language
[447619f](https://github.com/defi-wonderland/superchain-bridge-ui/pull/81/commits/447619f559bd4d8a08cf4e1cf357d83d33edc225)

2024-04-22 13:26 UTC, agusduha approved these changes

2024-04-22 13:29 UTC, merged